services:
  app:
    build:
      context: BUILD
      args:
        MAGENI_USERNAME: "admin"
        MAGENI_EMAIL: "admin@mageni.int"
        MAGENI_PASSWORD: "Password1"
    image: mageni
    hostname: mageni
    container_name: mageni
    restart: always
    ports:
      - 8443:443
